def get_card():
    return [
        {"suit": "♥", "rank": "2", "image_file": "carddeck/2_of_hearts.png"},
        {"suit": "♥", "rank": "3", "image_file": "carddeck/3_of_hearts.png"},
        {"suit": "♥", "rank": "4", "image_file": "carddeck/4_of_hearts.png"},
        {"suit": "♥", "rank": "5", "image_file": "carddeck/5_of_hearts.png"},
        {"suit": "♥", "rank": "6", "image_file": "carddeck/6_of_hearts.png"},
        {"suit": "♥", "rank": "7", "image_file": "carddeck/7_of_hearts.png"},
        {"suit": "♥", "rank": "8", "image_file": "carddeck/8_of_hearts.png"},
        {"suit": "♥", "rank": "9", "image_file": "carddeck/9_of_hearts.png"},
        {"suit": "♥", "rank": "10", "image_file": "carddeck/10_of_hearts.png"},
        {"suit": "♥", "rank": "J", "image_file": "carddeck/jack_of_hearts2.png"},
        {"suit": "♥", "rank": "Q", "image_file": "carddeck/queen_of_hearts2.png"},
        {"suit": "♥", "rank": "K", "image_file": "carddeck/king_of_hearts2.png"},
        {"suit": "♥", "rank": "A", "image_file": "carddeck/3ace_of_hearts.png"},

        {"suit": "♦", "rank": "2", "image_file": "carddeck/2_of_diamonds.png"},
        {"suit": "♦", "rank": "3", "image_file": "carddeck/3_of_diamonds.png"},
        {"suit": "♦", "rank": "4", "image_file": "carddeck/4_of_diamonds.png"},
        {"suit": "♦", "rank": "5", "image_file": "carddeck/5_of_diamonds.png"},
        {"suit": "♦", "rank": "6", "image_file": "carddeck/6_of_diamonds.png"},
        {"suit": "♦", "rank": "7", "image_file": "carddeck/7_of_diamonds.png"},
        {"suit": "♦", "rank": "8", "image_file": "carddeck/8_of_diamonds.png"},
        {"suit": "♦", "rank": "9", "image_file": "carddeck/9_of_diamonds.png"},
        {"suit": "♦", "rank": "10", "image_file": "carddeck/10_of_diamonds.png"},
        {"suit": "♦", "rank": "J", "image_file": "carddeck/jack_of_diamonds2.png"},
        {"suit": "♦", "rank": "Q", "image_file": "carddeck/queen_of_diamonds2.png"},
        {"suit": "♦", "rank": "K", "image_file": "carddeck/king_of_diamonds2.png"},
        {"suit": "♦", "rank": "A", "image_file": "carddeck/ace_of_diamonds.png"},

        
        {"suit": "♠", "rank": "2", "image_file": "carddeck/2_of_spades.png"},
        {"suit": "♠", "rank": "3", "image_file": "carddeck/3_of_spades.png"},
        {"suit": "♠", "rank": "4", "image_file": "carddeck/4_of_spades.png"},
        {"suit": "♠", "rank": "5", "image_file": "carddeck/5_of_spades.png"},
        {"suit": "♠", "rank": "6", "image_file": "carddeck/6_of_spades.png"},
        {"suit": "♠", "rank": "7", "image_file": "carddeck/7_of_spades.png"},
        {"suit": "♠", "rank": "8", "image_file": "carddeck/8_of_spades.png"},
        {"suit": "♠", "rank": "9", "image_file": "carddeck/9_of_spades.png"},
        {"suit": "♠", "rank": "10", "image_file": "carddeck/10_of_spades.png"},
        {"suit": "♠", "rank": "J", "image_file": "carddeck/jack_of_spades.png"},
        {"suit": "♠", "rank": "Q", "image_file": "carddeck/queen_of_spades.png"},
        {"suit": "♠", "rank": "K", "image_file": "carddeck/king_2_of_spades.png"},
        {"suit": "♠", "rank": "A", "image_file": "carddeck/ace_of_spades.png"},


        {"suit": "♣", "rank": "2", "image_file": "carddeck/2_of_clubs.png"},
        {"suit": "♣", "rank": "3", "image_file": "carddeck/3_of_clubs.png"},
        {"suit": "♣", "rank": "4", "image_file": "carddeck/4_of_clubs.png"},
        {"suit": "♣", "rank": "5", "image_file": "carddeck/5_of_clubs.png"},
        {"suit": "♣", "rank": "6", "image_file": "carddeck/6_of_clubs.png"},
        {"suit": "♣", "rank": "7", "image_file": "carddeck/7_of_clubs.png"},
        {"suit": "♣", "rank": "8", "image_file": "carddeck/8_of_clubs.png"},
        {"suit": "♣", "rank": "9", "image_file": "carddeck/9_of_clubs.png"},
        {"suit": "♣", "rank": "10", "image_file": "carddeck/10_of_clubs.png"},
        {"suit": "♣", "rank": "J", "image_file": "carddeck/jack_of_clubs2.png"},
        {"suit": "♣", "rank": "Q", "image_file": "carddeck/queen_of_clubs2.png"},
        {"suit": "♣", "rank": "K", "image_file": "carddeck/king_of_clubs2.png"},
        {"suit": "♣", "rank": "A", "image_file": "carddeck/ace_of_clubs.png"},

        
    ]